<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="display:flex; justify-content:center;align-items:center;">
  <div class="card card-outline card-primary">
  <div class="card-body">
    <div style="display:flex; justify-content:center;"><h4><b>Sobre Nós</b></h4></div>
    <div class="row mb-3">  
      <div class="col-3"></div>
      <div class="col-9">
        <img src="{{URL}}/img/{{imagem}}" style="border-radius:10px; border:solid 2px #212529;" width="270px" height="150px" alt="">
      </div>
    </div>
    <form name="post" id="formRegister" method="POST" enctype="multipart/form-data" action="{{URL}}/dashboard-admin/about/{{op_route}}{{id}}">
      <div class="input-group mb-3">
        <input type="file" class="form-control" value="{{imagem}}" name="imagem">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class=""></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <textarea name="descricao" class="form-control" name="descricao" placeholder="Descrição" cols="56" rows="8">{{descricao}}</textarea>
      </div>
      <div class="row">
        <div class="col-8">
          
        </div>
        <!-- /.col -->
        <div class="col-4">
          <button type="submit" class="btn btn-primary btn-block">Publicar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
  <div style="display:flex; justify-content:center;"><br/>{{status}}</div>
  </div>
  </div>
</div>
   