<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="display:flex;justify-content:center;align-items:center;">
  <div class="register-box">
  <div class="card card-outline card-primary">
  <div class="card-body">
  <div style="display:flex; justify-content:center;"><h4><b>Novo serviço</b></h4></div>
    <form name="register" id="formRegister" method="post" action="{{URL}}/dashboard-admin/services/store">
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="servico" placeholder="Serviço">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="categoria" placeholder="Categoria">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <textarea name="descricao" id="" name="descricao" placeholder="Descrição" cols="29" rows="4"></textarea>
      </div>
      <div>
        <div>Estado do serviço</div>
        <div class="input-group mb-3">
          <select name="estado" class="btn btn-light">
            <option value=""></option>
            <option value="1">Activar</option>
            <option value="0">Desactivar</option>
          </select>
        </div>
      </div>
      <div class="row">
        <div class="col-8">
          
        </div>
        <!-- /.col -->
        <div class="col-4">
          <button type="submit" class="btn btn-primary btn-block">Register</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <a href="{{URL}}/dashboard-admin/services" class="text-center">Voltar</a>
  </div>
  </div>
  <div style="display:flex; justify-content:center;"><br/>{{status}}</div>
  </div>
  </div>
</div>
   