<tr>
    <td>{{id}}</td>
    <td>{{servico}}</td>
    <td>{{categoria}}</td>
    <td>{{descricao}}</td>
    <td>{{estado}}</td>
    <td>{{time}}</td>
    <td style="width: 50px;" class="">
        <a href="{{URL}}/dashboard-admin/services/edit/{{id}}" class="far fa-edit" type="button" title="Editar"></a>
        <a class="far fa-trash-alt" onClick="visibilityBox({{id}});" type="button" title="Eliminar"></a>
    </td>
</tr>