<div class="col-lg-6 d-flex align-items-stretch" data-aos="fade-up">
    <div class="info-box">
    <i class="bx bx-map"></i>
    <h3>Nosso Endereço</h3>
    <p>{{endereco}}</p>
    </div>
</div>

<div class="col-lg-3 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
    <div class="info-box">
    <i class="bx bx-envelope"></i>
    <h3>Nosso Email</h3>
    <p>{{email}}</p>
    </div>
</div>

<div class="col-lg-3 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
    <div class="info-box ">
    <i class="bx bx-phone-call"></i>
    <h3>Liga para:</h3>
    <p>{{telefone1}}<br>{{telefone2}}</p>
    </div>
</div>

<div class="col-lg-12" data-aos="fade-up" data-aos-delay="300">
    <form action="forms/contact.php" method="post" role="form" class="php-email-form">
    <div class="form-row">
        <div class="col-lg-6 form-group">
        <input type="text" name="name" class="form-control" id="name" placeholder="Teu Nome" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
        <div class="validate"></div>
        </div>
        <div class="col-lg-6 form-group">
        <input type="email" class="form-control" name="email" id="email" placeholder="Teu email" data-rule="email" data-msg="Please enter a valid email" />
        <div class="validate"></div>
        </div>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="subject" id="subject" placeholder="Objectivo" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
        <div class="validate"></div>
    </div>
    <div class="form-group">
        <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Mensagem"></textarea>
        <div class="validate"></div>
    </div>
    <div class="mb-3">
        <div class="loading">Loading</div>
        <div class="error-message"></div>
        <div class="sent-message">Your message has been sent. Thank you!</div>
    </div>
    <div class="text-center"><button type="submit">Enviar Mensagem</button></div>
    </form>
</div>
