<div class="col-lg-4 col-md-6 portfolio-item filter-{{categoria}}">
    <div class="portfolio-wrap">
    <img src="{{URL}}/img/portfolio/{{imagem}}" class="img-fluid" alt="">
    <div class="portfolio-info">
        <h4>App 1</h4>
        <p>App</p>
        <div class="portfolio-links">
        <a href="{{URL}}/img/portfolio/{{imagem}}" data-gall="portfolioGallery" class="venobox" title="App 1"><i class="icofont-eye"></i></a>
        <a href="portfolio-details.html" title="More Details"><i class="icofont-external-link"></i></a>
        </div>
    </div>
    </div>
</div>