<div class="carousel-item {{active}}" style="background-image: url('{{URL}}/img/slide/{{imagem}}')">
    <div class="carousel-container">
    <div class="carousel-content container">
        <h2 class="animate__animated animate__fadeInDown">{{titulo}}</h2>
        <p class="animate__animated animate__fadeInUp">{{descricao}}</p>
        <a href="#about" class="btn-get-started animate__animated animate__fadeInUp scrollto">Saiba mais</a>
    </div>
    </div>
</div>