<div class="col-xl-3 col-lg-4 col-md-6" data-aos="fade-up">
    <div class="member">
    <div class="pic"><img src="{{URL}}/img/team/{{imagem}}" class="img-fluid" alt=""></div>
    <div class="member-info">
        <h4>{{nome}}</h4>
        <span>{{cargo}}</span>
        <div class="social">
        <a href="{{twitter}}"><i class="icofont-twitter"></i></a>
        <a href="{{facebook}}"><i class="icofont-facebook"></i></a>
        <a href="{{instagram}}"><i class="icofont-instagram"></i></a>
        <a href="{{linkedin}}"><i class="icofont-linkedin"></i></a>
        </div>
    </div>
    </div>
</div>