<div class="col-12">
    <div class="form-group">
    <label><h4>Telefones</h4><p style="color:#685f5f;">{{telefone1}} / {{telefone2}}</p></label>
    </div>
</div>
<div class="col-12">
    <div class="form-group">
    <label><h4>E-Mail</h4><p style="color:#685f5f;">{{email}}</p></label>
    </div>
</div>
<div class="col-12">
    <div class="form-group">
    <label><h4>Facebook</h4><p style="color:#685f5f;">{{facebook}}</p></label>
    </div>
</div>
<div class="col-12">
    <div class="form-group">
    <label><h4>Instagram</h4><p style="color:#685f5f;">{{instagram}}</p></label>
    </div>
</div>
<div class="col-12">
    <div class="form-group">
    <label><h4>Linkedin</h4><p style="color:#685f5f;">{{linkedin}}</p></label>
    </div>
</div>
<div class="col-12">
    <div class="form-group">
    <label><h4>Endereço</h4><p style="color:#685f5f;">{{endereco}}</p></label>
    </div>
</div>
