<tr>
    <td><img src="{{URL}}/img/portfolio/{{imagem}}" width="110px" height="60px" alt=""></td>
    <td>{{categoria}}</td>
    <td>{{descricao}}</td>
    <!--<td>{{descricao}}</td>-->
    <td style="width: 50px;" class="">
        <a href="{{URL}}/dashboard-admin/portfolio/edit/{{id}}" class="far fa-edit" type="button" title="Editar"></a>
        <a class="far fa-trash-alt" onClick="visibilityBox({{id}});" type="button" title="Eliminar"></a>
    </td>
</tr>