<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Rogerio Tuzolna">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{URL}}/css/style.css">
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{URL}}/img/favicon.png" rel="icon">
    <link href="{{URL}}/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{URL}}/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{URL}}/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="{{URL}}/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="{{URL}}/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="{{URL}}/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="{{URL}}/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="{{URL}}/assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{{URL}}/assets/css/style.css" rel="stylesheet">

    <title>{{title}}</title>
    <?php ?>
</head>
<body>
    <!-- ======= Top Bar ======= -->
    <section id="topbar" class="d-none d-lg-block">
        <div class="container clearfix">
        <div class="contact-info float-left">
            <i class="icofont-envelope"></i><a href="mailto:contact@example.com">{{email}}</a>
            <i class="icofont-phone"></i> {{telefone1}}/{{telefone2}}
        </div>
        <div class="social-links float-right">
            <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
            <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
            <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
            <a href="#" class="skype"><i class="icofont-skype"></i></a>
            <a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
        </div>
        </div>
    </section>
  <!-- ======= End top Bar ======= -->
  <!-- ======= Header ======= -->
    <header id="header">
        <div class="container">

        <div class="logo float-left">
            <h1 class="text-light"><a href="index.html"><span>Prestativ</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav class="nav-menu float-right d-none d-lg-block">
            <ul>
            <li class="active"><a href="{{URL}}/">Home</a></li>
            <li><a href="#about">Sobre Nos</a></li>
            <li><a href="#services">Serviços</a></li>
            <li><a href="#portfolio">Portfolio</a></li>
            <li><a href="#team">Equipa</a></li>
            <li class="drop-down"><a href="">Drop Down</a>
                <ul>
                <li><a href="#">Drop Down 1</a></li>
                <li class="drop-down"><a href="#">Drop Down 2</a>
                    <ul>
                    <li><a href="#">Deep Drop Down 1</a></li>
                    <li><a href="#">Deep Drop Down 2</a></li>
                    <li><a href="#">Deep Drop Down 3</a></li>
                    <li><a href="#">Deep Drop Down 4</a></li>
                    <li><a href="#">Deep Drop Down 5</a></li>
                    </ul>
                </li>
                <li><a href="#">Drop Down 3</a></li>
                <li><a href="#">Drop Down 4</a></li>
                <li><a href="#">Drop Down 5</a></li>
                </ul>
            </li>
            <li><a href="#contact">Contacte Nos</a></li>
            </ul>
        </nav><!-- .nav-menu -->

        </div>

    </header><!-- End Header -->

        <!-- ======= Hero Section ======= -->
    <section id="hero">
        {{slide}}
    </section><!-- End Hero -->
    <main id="main">

        <!-- ======= About Us Section ======= -->
        <section id="about" class="about">
            {{about}}
        </section><!-- End About Us Section -->

        <!-- ======= About Lists Section ======= -->
        <section class="about-lists">
        <div class="container">

            <div class="row no-gutters">

            <div class="col-lg-4 col-md-6 content-item" data-aos="fade-up">
                <span>01</span>
                <h4>Lorem Ipsum</h4>
                <p>Ulamco laboris nisi ut aliquip ex ea commodo consequat. Et consectetur ducimus vero placeat</p>
            </div>

            <div class="col-lg-4 col-md-6 content-item" data-aos="fade-up" data-aos-delay="100">
                <span>02</span>
                <h4>Repellat Nihil</h4>
                <p>Dolorem est fugiat occaecati voluptate velit esse. Dicta veritatis dolor quod et vel dire leno para dest</p>
            </div>

            <div class="col-lg-4 col-md-6 content-item" data-aos="fade-up" data-aos-delay="200">
                <span>03</span>
                <h4> Ad ad velit qui</h4>
                <p>Molestiae officiis omnis illo asperiores. Aut doloribus vitae sunt debitis quo vel nam quis</p>
            </div>

            <div class="col-lg-4 col-md-6 content-item" data-aos="fade-up" data-aos-delay="300">
                <span>04</span>
                <h4>Repellendus molestiae</h4>
                <p>Inventore quo sint a sint rerum. Distinctio blanditiis deserunt quod soluta quod nam mider lando casa</p>
            </div>

            <div class="col-lg-4 col-md-6 content-item" data-aos="fade-up" data-aos-delay="400">
                <span>05</span>
                <h4>Sapiente Magnam</h4>
                <p>Vitae dolorem in deleniti ipsum omnis tempore voluptatem. Qui possimus est repellendus est quibusdam</p>
            </div>

            <div class="col-lg-4 col-md-6 content-item" data-aos="fade-up" data-aos-delay="500">
                <span>06</span>
                <h4>Facilis Impedit</h4>
                <p>Quis eum numquam veniam ea voluptatibus voluptas. Excepturi aut nostrum repudiandae voluptatibus corporis sequi</p>
            </div>

            </div>

        </div>
        
        </section><!-- End About Lists Section -->

        
        <!-- ======= Services Section ======= -->
        <section id="services" class="services">
            <div class="container">
                <div class="section-title">
                    <h2>Serviços</h2>
                </div>
                {{services}}
                <div class="col-lg-12" data-aos="fade-up" data-aos-delay="300">
                    <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                        <div class="form-row">
                            <div class="col-lg-6 form-group">
                                <input type="text" name="name" class="form-control" id="name" placeholder="Teu Nome" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                                <div class="validate"></div>
                            </div>
                            <div class="col-lg-6 form-group">
                                <input type="email" class="form-control" name="email" id="email" placeholder="Teu email" data-rule="email" data-msg="Please enter a valid email" />
                                <div class="validate"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="subject" id="subject" placeholder="Objectivo" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                            <div class="validate"></div>
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Mensagem"></textarea>
                            <div class="validate"></div>
                        </div>
                        <div class="mb-3">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            <div class="sent-message">Your message has been sent. Thank you!</div>
                        </div>
                        <div class="text-center"><button type="submit">Enviar Mensagem</button></div>
                    </form>
                </div>

            </div>
        </section><!-- End Services Section -->
    
        <!-- ======= Our Portfolio Section ======= -->
        <section id="portfolio" class="portfolio section-bg">
        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="section-title">
                <h2>Portfolio</h2>
                <p>Alguns trabalhos prestados por intermédio da <b>Prestativ</b>.</p>
            </div>

            {{portfolio}}
        </div>
        </section><!-- End Our Portfolio Section -->

        <!-- ======= Our Team Section ======= -->
        <section id="team" class="team">
            {{team}}
        </section><!-- End Our Team Section -->

        <!-- ======= Frequently Asked Questions Section ======= -->
        <section id="faq" class="faq section-bg">
        <div class="container">

            <div class="section-title">
            <h2>Frequently Asked Questions</h2>
            </div>

            <div class="row  d-flex align-items-stretch">

            <div class="col-lg-6 faq-item" data-aos="fade-up">
                <h4>Non consectetur a erat nam at lectus urna duis?</h4>
                <p>
                Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.
                </p>
            </div>

            <div class="col-lg-6 faq-item" data-aos="fade-up" data-aos-delay="100">
                <h4>Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque?</h4>
                <p>
                Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim.
                </p>
            </div>

            <div class="col-lg-6 faq-item" data-aos="fade-up" data-aos-delay="200">
                <h4>Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi?</h4>
                <p>
                Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Faucibus pulvinar elementum integer enim. Sem nulla pharetra diam sit amet nisl suscipit. Rutrum tellus pellentesque eu tincidunt. Lectus urna duis convallis convallis tellus.
                </p>
            </div>

            <div class="col-lg-6 faq-item" data-aos="fade-up" data-aos-delay="300">
                <h4>Ac odio tempor orci dapibus. Aliquam eleifend mi in nulla?</h4>
                <p>
                Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim.
                </p>
            </div>

            <div class="col-lg-6 faq-item" data-aos="fade-up" data-aos-delay="400">
                <h4>Tempus quam pellentesque nec nam aliquam sem et tortor consequat?</h4>
                <p>
                Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est ante in. Nunc vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est. Purus gravida quis blandit turpis cursus in
                </p>
            </div>

            <div class="col-lg-6 faq-item" data-aos="fade-up" data-aos-delay="500">
                <h4>Tortor vitae purus faucibus ornare. Varius vel pharetra vel turpis nunc eget lorem dolor?</h4>
                <p>
                Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer malesuada nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut venenatis tellus in metus vulputate eu scelerisque.
                </p>
            </div>

            </div>

        </div>
        </section><!-- End Frequently Asked Questions Section -->

        <!-- ======= Contact Us Section ======= -->
        <section id="contact" class="contact">
            {{contacts}}
        </section><!-- End Contact Us Section -->

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
        <div class="container">
            <div class="row">

            <div class="col-lg-3 col-md-6 footer-info">
                <h3>Prestativ</h3>
                <p>
                {{endereco}}<br><br>
                <strong>Telefone:</strong> {{telefone1}}/{{telefone2}}<br>
                <strong>Email:</strong> {{email}}<br>
                </p>
                <div class="social-links mt-3">
                <a href="{{twitter}}" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="{{facebook}}" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="{{instagram}}" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="{{linkedin}}" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                </div>
            </div>

            <div class="col-lg-2 col-md-6 footer-links">
                <h4>Outros Links</h4>
                <ul>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Termos de serviços</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Politica de Privacidade</a></li>
                </ul>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
                <h4>Nossos Serviços</h4>
                <ul>
                    {{services2}}
                </ul>
            </div>

            <div class="col-lg-4 col-md-6 footer-newsletter">
                <h4>Nosso Newsletter</h4>
                <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                <form action="" method="post">
                <input type="email" name="email"><input type="submit" value="Subscrever">
                </form>

            </div>

            </div>
        </div>
        </div>

        <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Prestativ</span></strong>. Todos direitos reservado
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mamba-one-page-bootstrap-template-free/ -->
            Dev. by Rogério Tuzolana</a>
        </div>
        </div>

    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

    <!-- Vendor JS Files -->
    <script src="{{URL}}/assets/vendor/jquery/jquery.min.js"></script>
    <script src="{{URL}}/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="{{URL}}/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="{{URL}}/assets/vendor/php-email-form/validate.js"></script>
    <script src="{{URL}}/assets/vendor/jquery-sticky/jquery.sticky.js"></script>
    <script src="{{URL}}/assets/vendor/venobox/venobox.min.js"></script>
    <script src="{{URL}}/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="{{URL}}/assets/vendor/counterup/counterup.min.js"></script>
    <script src="{{URL}}/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="{{URL}}/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="{{URL}}/assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="{{URL}}/js/main.js"></script>
</body>
</html>