<div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
    <div class="icon"><i class="icofont-computer"></i></div>
    <h4 class="title"><a href="">{{nome}}</a></h4>
    <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
</div>
<div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
    <div class="icon"><i class="icofont-chart-bar-graph"></i></div>
    <h4 class="title"><a href="">Dolor Sitema</a></h4>
    <p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>
</div>
<div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
    <div class="icon"><i class="icofont-earth"></i></div>
    <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
    <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
</div>
<div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
    <div class="icon"><i class="icofont-image"></i></div>
    <h4 class="title"><a href="">Magni Dolores</a></h4>
    <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
</div>
<div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
    <div class="icon"><i class="icofont-settings"></i></div>
    <h4 class="title"><a href="">Nemo Enim</a></h4>
    <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
</div>
<div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="500">
    <div class="icon"><i class="icofont-tasks-alt"></i></div>
    <h4 class="title"><a href="">Eiusmod Tempor</a></h4>
    <p class="description">Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi</p>
</div>