<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="display:flex; justify-content:center;align-items:center;">
  <div class="card card-outline card-primary">
  <div class="card-body">
    <div style="display:flex; justify-content:center;"><h4><b>Novo Membro</b></h4></div>
    <form  name="post" id="formRegister" method="POST" enctype="multipart/form-data" action="{{URL}}/dashboard-admin/team/store">
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="nome" placeholder="Nome">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class=""></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="cargo" placeholder="Cargo">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class=""></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="file" class="form-control" name="imagem" placeholder="Imagem">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class=""></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="facebook" placeholder="Facebook">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class=""></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="instagram" placeholder="Instagram">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class=""></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="twitter" placeholder="Twitter">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class=""></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="linkedin" placeholder="Linkedin">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class=""></span>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-8">
        </div>
        <!-- /.col -->
        <div class="col-4">
          <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <a href="{{URL}}/dashboard-admin/team" class="text-center">Voltar</a>
  </div>
  <div style="display:flex; justify-content:center;"><br/>{{status}}</div>
  </div>
  </div>
</div>
   