<tr>
    <td>{{id}}</td>
    <td>{{nome}}</td>
    <td>{{cargo}}</td>
    <td><img src="{{URL}}/img/team/{{imagem}}" width="110px" height="60px" alt=""></td>
    <td>{{facebook}}</td>
    <td>{{instagram}}</td>
    <td>{{twitter}}</td>
    <td>{{linkedin}}</td>
    <!--<td>{{descricao}}</td>-->
    <td style="width: 50px;" class="">
        <a href="{{URL}}/dashboard-admin/team/edit/{{id}}" class="far fa-edit" type="button" title="Editar"></a>
        <a class="far fa-trash-alt" onClick="visibilityBox({{id}});" type="button" title="Eliminar"></a>
    </td>
</tr>